name: Reference linter
on:
  push:
    paths:
      - 'en_US/**.json'
      - '.github/workflows/reference_lint.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'en_US/**.json'
      - '.github/workflows/reference_lint.yaml'
    branches:
      - main
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check strings
        run: |
          python .github/scripts/webext_reference.py --path en_US
